package cl.javier.salaremote.ui;

import android.content.Context;
import android.graphics.*;
import android.view.*;
import java.util.*;

public final class RemoteView extends View {
    public interface Actions { void onConnectTap(); void onKey(int keyCode); }
    private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG); private final Actions actions; private final List<Hit> hits=new ArrayList<>();
    private int mode=0; private String deviceName="Conectar TV"; private boolean connected=false; private float downX,downY;
    public RemoteView(Context c,Actions a){super(c);actions=a;setBackgroundColor(Color.rgb(18,15,21));}
    public void setDevice(String n,boolean ok){deviceName=n==null?"Conectar TV":n;connected=ok;invalidate();}
    @Override protected void onDraw(Canvas c){super.onDraw(c);hits.clear();float w=getWidth(),h=getHeight(),d=getResources().getDisplayMetrics().density,top=18*d;
        RectF pill=new RectF(w*.23f,top,w*.77f,top+52*d);p.setColor(Color.rgb(66,65,70));c.drawRoundRect(pill,28*d,28*d,p);p.setColor(connected?Color.rgb(80,200,80):Color.rgb(255,153,0));c.drawCircle(pill.left+20*d,pill.centerY(),6*d,p);text(c,deviceName,pill.centerX()+8*d,pill.centerY()+7*d,19*d,Color.WHITE,true);hits.add(new Hit(pill,-100));
        circle(c,54*d,top+99*d,31*d,"⏻",Color.rgb(220,65,65),26*d,26);
        float sy=top+98*d;RectF s=new RectF(w*.34f,sy-28*d,w*.66f,sy+28*d);p.setColor(Color.rgb(48,46,53));c.drawRoundRect(s,24*d,24*d,p);float t=s.width()/3;RectF sel=new RectF(s.left+t*mode,s.top,s.left+t*(mode+1),s.bottom);p.setColor(Color.rgb(255,153,0));c.drawRoundRect(sel,24*d,24*d,p);text(c,"✥",s.left+t*.5f,s.centerY()+7*d,22*d,mode==0?Color.WHITE:Color.GRAY,true);text(c,"▱",s.left+t*1.5f,s.centerY()+7*d,22*d,mode==1?Color.WHITE:Color.GRAY,true);text(c,"⠿",s.left+t*2.5f,s.centerY()+7*d,22*d,mode==2?Color.WHITE:Color.GRAY,true);hits.add(new Hit(new RectF(s.left,s.top,s.left+t,s.bottom),-10));hits.add(new Hit(new RectF(s.left+t,s.top,s.left+2*t,s.bottom),-11));hits.add(new Hit(new RectF(s.left+2*t,s.top,s.right,s.bottom),-12));
        float y=top+145*d;if(mode==0)dpad(c,w,y,d);else if(mode==1)touch(c,w,y,d);else numbers(c,w,y,d);common(c,w,h,d);}
    private void dpad(Canvas c,float w,float y,float d){float cx=w/2,cy=y+150*d,r=135*d,in=67*d;p.setColor(Color.rgb(48,46,53));c.drawCircle(cx,cy,r,p);stroke(c,Color.rgb(255,174,80),1.5f*d);c.drawCircle(cx,cy,r,p);c.drawCircle(cx,cy,in,p);fill();text(c,"▲",cx,cy-r+43*d,19*d,0xffff9900,true);text(c,"▼",cx,cy+r-30*d,19*d,0xffff9900,true);text(c,"◀",cx-r+37*d,cy+7*d,19*d,0xffff9900,true);text(c,"▶",cx+r-37*d,cy+7*d,19*d,0xffff9900,true);text(c,"OK",cx,cy+8*d,20*d,0xffff9900,true);hits.add(new Hit(new RectF(cx-55*d,cy-r,cx+55*d,cy-in),19));hits.add(new Hit(new RectF(cx-55*d,cy+in,cx+55*d,cy+r),20));hits.add(new Hit(new RectF(cx-r,cy-55*d,cx-in,cy+55*d),21));hits.add(new Hit(new RectF(cx+in,cy-55*d,cx+r,cy+55*d),22));hits.add(new Hit(new RectF(cx-in,cy-in,cx+in,cy+in),23));}
    private void touch(Canvas c,float w,float y,float d){RectF r=new RectF(22*d,y,w-22*d,y+300*d);p.setColor(Color.rgb(48,46,53));c.drawRoundRect(r,22*d,22*d,p);stroke(c,Color.rgb(255,174,80),1.5f*d);c.drawRoundRect(r,22*d,22*d,p);fill();text(c,"Desliza o toca para seleccionar.",r.centerX(),r.centerY()+8*d,20*d,Color.WHITE,true);hits.add(new Hit(r,-50));}
    private void numbers(Canvas c,float w,float y,float d){float[] xs={w*.24f,w*.5f,w*.76f};int n=1;for(int row=0;row<3;row++)for(int col=0;col<3;col++)oval(c,xs[col],y+15*d+row*94*d,String.valueOf(n),7+n++,d);oval(c,w*.5f,y+15*d+3*94*d,"0",7,d);}
    private void common(Canvas c,float w,float h,float d){float y=h-255*d;RectF vol=new RectF(22*d,y-60*d,108*d,y+125*d);p.setColor(Color.rgb(47,45,52));c.drawRoundRect(vol,42*d,42*d,p);text(c,"+",vol.centerX(),vol.top+48*d,34*d,Color.WHITE,false);text(c,"VOL",vol.centerX(),vol.centerY()+7*d,22*d,Color.WHITE,true);text(c,"−",vol.centerX(),vol.bottom-28*d,34*d,Color.WHITE,false);hits.add(new Hit(new RectF(vol.left,vol.top,vol.right,vol.centerY()),24));hits.add(new Hit(new RectF(vol.left,vol.centerY(),vol.right,vol.bottom),25));circle(c,w*.36f,y-48*d,44*d,"↶",Color.WHITE,28*d,4);circle(c,w*.64f,y-48*d,44*d,"⌂",Color.WHITE,26*d,3);circle(c,w*.36f,y+49*d,38*d,"MUTE",Color.WHITE,13*d,164);circle(c,w*.64f,y+49*d,38*d,"▶Ⅱ",Color.WHITE,18*d,85);RectF ch=new RectF(w-108*d,y-60*d,w-22*d,y+125*d);p.setColor(Color.rgb(47,45,52));c.drawRoundRect(ch,42*d,42*d,p);text(c,"+\nCH",ch.centerX(),ch.centerY(),18*d,Color.WHITE,true);hits.add(new Hit(new RectF(ch.left,ch.top,ch.right,ch.centerY()),166));hits.add(new Hit(new RectF(ch.left,ch.centerY(),ch.right,ch.bottom),167));}
    private void circle(Canvas c,float x,float y,float r,String s,int color,float size,int code){p.setColor(Color.rgb(47,45,52));c.drawCircle(x,y,r,p);text(c,s,x,y+size*.28f,size,color,true);hits.add(new Hit(new RectF(x-r,y-r,x+r,y+r),code));}
    private void oval(Canvas c,float x,float y,String s,int code,float d){RectF r=new RectF(x-54*d,y-39*d,x+54*d,y+39*d);stroke(c,Color.rgb(255,174,80),1.5f*d);c.drawRoundRect(r,39*d,39*d,p);fill();text(c,s,x,y+7*d,21*d,Color.WHITE,true);hits.add(new Hit(r,code));}
    private void text(Canvas c,String s,float x,float y,float size,int color,boolean bold){p.setColor(color);p.setTextSize(size);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.create("sans",bold?Typeface.BOLD:Typeface.NORMAL));for(String line:s.split("\n")){c.drawText(line,x,y,p);y+=size;}}
    private void stroke(Canvas c,int color,float width){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(width);p.setColor(color);}private void fill(){p.setStyle(Paint.Style.FILL);}
    @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()==MotionEvent.ACTION_DOWN){downX=e.getX();downY=e.getY();return true;}if(e.getAction()==MotionEvent.ACTION_UP){for(Hit hit:hits)if(hit.r.contains(downX,downY)){int code=hit.c;if(code==-100)actions.onConnectTap();else if(code<=-10&&code>=-12){mode=-10-code;invalidate();}else if(code==-50){float dx=e.getX()-downX,dy=e.getY()-downY,th=35*getResources().getDisplayMetrics().density;if(Math.abs(dx)<th&&Math.abs(dy)<th)actions.onKey(23);else if(Math.abs(dx)>Math.abs(dy))actions.onKey(dx>0?22:21);else actions.onKey(dy>0?20:19);}else actions.onKey(code);performClick();return true;}}return true;}
    @Override public boolean performClick(){super.performClick();return true;} private static final class Hit{final RectF r;final int c;Hit(RectF r,int c){this.r=new RectF(r);this.c=c;}}
}
